[SPBU-21.B10] Task 2.2 Марилова Ксения
KseniaMarilova/spbu_c_homeworks pull request #13
Opened 2021-10-17 21:35 UTC by KseniaMarilova

2021-11-06 13:49 UTC, ArtyomLobanov requested changes

2021-11-06 13:49 UTC, ArtyomLobanov commented on homework2/task2.2.c
> +    return;
Имхо в данном случае вместо return-ов проще было объединить все внешние if-ы в if-else. Кстати, два вложенных if-а тоже можно объединить при желании.
```cpp
if (!strcmp("INSERT", command) && !delete (list, argument1, argument2)) 
    printf("Message");
else if (!strcmp("INSERT", command) && !insert(list, argument1, argument2)) 
    printf("Message");
...
```

2021-11-06 13:49 UTC, ArtyomLobanov commented on homework2/task2.2.c
> +    for (ListElement* current = line->head->next; current; current = current->next)
А почему вы не с list->head начинаете?

2021-11-06 13:49 UTC, ArtyomLobanov commented on library/ListOfChar/list.c
> +        line->head = createListElemet(0);
А, вы фейковый элемент в начале списка храните. Элегантно! 👍

2021-11-06 13:49 UTC, ArtyomLobanov commented on library/ListOfChar/list.c
> +        }
Такое ощущение, что в данном конкретном случае for даже в минус сыграл. У вас три переменные, две из которых дублируют друг друга. По факту переменная цикла лишняя.
```cpp
ListElement* fragmentPointer = fragment->head;
ListElement* listPointer = currentStart;
while (fragmentPointer->next && listPointer ->next) {
    if (fragmentPointer->next->symbol != listPointer->next->symbol)
        break;
    fragmentPointer = fragmentPointer->next;
    listPointer = listPointer->next;
}
```

2021-11-06 13:49 UTC, ArtyomLobanov commented on library/ListOfChar/list.c
> +        return false;
Утечка памяти, если не нашёлся только один из фрагментов, то память из под второго нужно очистить. Кроме того, если foundStart == NULL, то вот здесь `foundStart->end` вы обращаетесь по нулевому адресу.

2021-11-06 13:49 UTC, ArtyomLobanov commented on library/ListOfChar/list.c
> +    return true;
Если удаляется фрагмент из конца списка, то нужно обновить указатель на хвост списка (list->tail)

2021-11-06 13:49 UTC, ArtyomLobanov commented on homework2/task2.2.c
> +        List* argument2 = readDna(input);
Вы не очищаете память из-под списков. Только будьте осторожны, ведь элементы этих списков вы переиспользуете в dna. Скажем, пусть insert и replace, если они забирают себе ListElement-ы из аргумента, обнуляют ему указатели на голову и хвост. Либо, что более правильное решение с точки зрения интерфейса, пусть создают копии желаемых элементов. В любом случае в этом цикле после выполнения операций необходимо освободить память из-под аргументов.

2021-11-06 13:51 UTC, ArtyomLobanov commented
Исправляйте утечки памяти. Срок – неделя.

2021-11-12 21:34 UTC, KseniaMarilova commented on homework2/task2.2.c
> +    return;
Если вложенные if объединить, то если команды успешные, будет выполняться последний else всегда

2021-12-18 05:19 UTC, ArtyomLobanov approved these changes

2021-12-18 05:19 UTC, ArtyomLobanov commented
Ок

2021-12-22 04:42 UTC, merged